### PR TITLE
Support for developing under virtual environments

### PR DESCRIPTION
**Pull request by dpapathanasiou**
Hi @calpaterson 

First of all, nice project!

This pull request enables development under virtual environments more easily, by introducing a `requirements.txt` file, with the corresponding updates to `MANIFEST.in` and `setup.py` so that the package still builds correctly.

### CODE REVIEW

**Comment by calpaterson** [comment]
Hi - thanks for taking the time to submit this!

A requirements file isn't necessary to develop a setuptools project under a virtual environment, usually you'd do `pip install -e .` to install (`-e` is for "editable", meaning by symlink) the package.  That will draw in the dependencies listed in `setup.py`.  In the case of csvbase I do `pip install -e .[tests]` to install all the other developer specific requirements as well.

I think your documentation is great though, would you mind if I take that from this branch (I'll keep your commit byline intact so you retain credit :))?

**Comment by dpapathanasiou** [comment]
Well, it's your project, so feel free to use as much or as little of it as you see fit :)

Using `requirements.txt` is somewhat subjective, but I like it better b/c it cleans up `setup.py`, and people are probably more familiar with `pip install -r requirements.txt` than `pip install -e`

**Comment by calpaterson** [comment]
> Using `requirements.txt` is somewhat subjective, but I like it better b/c it cleans up `setup.py`, and people are probably more familiar with `pip install -r requirements.txt` than `pip install -e`

This is a good point.  I kept the requirements.txt but split out the tests dependencies because I prefer not to send those to prod.

I made setup.py reference the requirements.txt files - that has to keep working - that's how I package up and deploy to prod.

I (lightly!) edited your docs (many thanks!!) and made them the start of a new HACKING.md file reference from the README.

Thanks so much mate.  If you have more ideas, please please let me know :)

**Comment by calpaterson** [comment]
I probably should find a way to make the systemd dependency optional, that is probably a pretty big bear to fight if you're on macos

**Pull request merged**
